# Stemset Configuration
# Multiple profiles allow you to process different recording sources

strategies:
#################################
  demucs_ft:
    _: "htdemucs_ft"
    vocals: vocals
    bass: bass
    drums: drums
    other: other

  hdemucs_mmi:
    _: "hdemucs_mmi"
    vocals: vocals
    bass: bass
    drums: drums
    other: other

  successive:
    _: "vocals_mel_band_roformer.ckpt"
    vocals: vocals
    not_vocals: 
      _: "kuielab_b_drums.onnx"
      drums: drums
      not_drums:
        _: "kuielab_a_bass.onnx"
        bass: bass
        not_bass: other

profiles:
#################################
  - name: "h4n"
    source_folder: "/Volumes/H4N_SD/STEREO"
    strategy: "htdemucs_ft"
    output_format: "opus"
    opus_bitrate: 192

  - name: "one"
    source_folder: "./input/one"
    strategy: "successive"
    output_format: "opus"
    opus_bitrate: 192

