# Stemset Configuration
# Multiple profiles allow you to process different recording sources

profiles:
  - name: "example-profile"
    source_folder: "/path/to/your/recordings"
    target_lufs: -23.0
    stem_gains:
      vocals: 0.0
      drums: -2.0
      bass: 1.0
      other: -1.0

# Add more profiles as needed:
# - name: "live-shows"
#   source_folder: "/path/to/live/recordings"
#   target_lufs: -20.0
#   stem_gains:
#     vocals: 2.0
#     drums: 0.0
#     bass: 1.0
#     other: 0.0
