# Stemset Configuration
# Multiple profiles allow you to process different recording sources

# Authentication (optional - comment out to disable auth)
# Environment variables will be substituted: ${VAR_NAME}
auth:
  allowed_emails:
    - sastraxi@gmail.com
  google_client_id: ${GOOGLE_CLIENT_ID}
  google_client_secret: ${GOOGLE_CLIENT_SECRET}
  jwt_secret: ${JWT_SECRET}
  redirect_uri: ${OAUTH_REDIRECT_URI}

strategies:
#################################
  htdemucs_ft:
    _: "htdemucs_ft"
    vocals: vocals
    bass: bass
    drums: drums
    other: other

  hdemucs_mmi:
    _: "hdemucs_mmi"
    vocals: vocals
    bass: bass
    drums: drums
    other: other

  successive:
    _: "vocals_mel_band_roformer.ckpt"
    vocals: vocals
    not_vocals: 
      _: "kuielab_b_drums.onnx"
      drums: drums
      not_drums:
        _: "kuielab_a_bass.onnx"
        bass: bass
        not_bass: other

profiles:
#################################
  - name: "h4n"
    source_folder: "/Volumes/H4N_SD/STEREO"
    strategy: "hdemucs_mmi"
    output:
      format: "opus"
      bitrate: 192

  - name: "one"
    source_folder: "./input/one"
    strategy: "htdemucs_ft"
    output:
      format: "opus"
      bitrate: 192

