# Stemset Configuration
# Multiple profiles allow you to process different recording sources

profiles:
  - name: "h4n"
    source_folder: "/Volumes/H4N_SD/STEREO"
    target_lufs: -23.0
    stem_gains:
      vocals: 0.0
      drums: -2.0
      bass: 1.0
      other: -1.0
    output_format: "opus"  # "opus" or "wav"
    opus_bitrate: 192      # Bitrate in kbps (96-512, recommended: 128-256)

# Add more profiles as needed:
# - name: "live-shows"
#   source_folder: "/path/to/live/recordings"
#   target_lufs: -20.0
#   stem_gains:
#     vocals: 2.0
#     drums: 0.0
#     bass: 1.0
#     other: 0.0
#   output_format: "opus"
#   opus_bitrate: 256  # Higher quality for archival
