"""Add idempotency and audio file link to recordings

Revision ID: 5bc0dc79f976
Revises: 3bef59a75dbb
Create Date: 2025-11-14 01:57:44.898580

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5bc0dc79f976"
down_revision: Union[str, Sequence[str], None] = "3bef59a75dbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recordings", sa.Column("audio_file_id", sa.Uuid(), nullable=True))
    op.add_column(
        "recordings",
        sa.Column("stems_metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "recordings", sa.Column("separated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "recordings", sa.Column("clips_detected_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "recordings", sa.Column("converted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("recordings", sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        op.f("ix_recordings_audio_file_id"), "recordings", ["audio_file_id"], unique=False
    )
    op.create_foreign_key(
        "fk_recordings_audio_file_id", "recordings", "audio_files", ["audio_file_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_recordings_audio_file_id", "recordings", type_="foreignkey")
    op.drop_index(op.f("ix_recordings_audio_file_id"), table_name="recordings")
    op.drop_column("recordings", "uploaded_at")
    op.drop_column("recordings", "converted_at")
    op.drop_column("recordings", "clips_detected_at")
    op.drop_column("recordings", "separated_at")
    op.drop_column("recordings", "stems_metadata_json")
    op.drop_column("recordings", "audio_file_id")
    # ### end Alembic commands ###
