"""Add clip boundaries json cache

Revision ID: c30e8283f491
Revises: 32e9ec064c25
Create Date: 2025-11-14 02:21:58.397692

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c30e8283f491"
down_revision: Union[str, Sequence[str], None] = "32e9ec064c25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recordings",
        sa.Column("clip_boundaries_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recordings", "clip_boundaries_json")
    # ### end Alembic commands ###
