"""add_drive_webhook_subscriptions

Revision ID: 012
Revises: 011_normalize_audiofile
Create Date: 2025-11-20 23:12:12.275004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '012'
down_revision: Union[str, Sequence[str], None] = '011_normalize_audiofile'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_webhook_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('drive_folder_id', sa.String(), nullable=False),
    sa.Column('expiration_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drive_webhook_subscriptions_channel_id'), 'drive_webhook_subscriptions', ['channel_id'], unique=True)
    op.create_index(op.f('ix_drive_webhook_subscriptions_is_active'), 'drive_webhook_subscriptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_drive_webhook_subscriptions_profile_id'), 'drive_webhook_subscriptions', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drive_webhook_subscriptions_profile_id'), table_name='drive_webhook_subscriptions')
    op.drop_index(op.f('ix_drive_webhook_subscriptions_is_active'), table_name='drive_webhook_subscriptions')
    op.drop_index(op.f('ix_drive_webhook_subscriptions_channel_id'), table_name='drive_webhook_subscriptions')
    op.drop_table('drive_webhook_subscriptions')
    # ### end Alembic commands ###
