"""Populate audio file id and make non-nullable

Revision ID: 32e9ec064c25
Revises: 5bc0dc79f976
Create Date: 2025-11-14 02:00:13.181261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e9ec064c25'
down_revision: Union[str, Sequence[str], None] = '5bc0dc79f976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    recordings_table = sa.table('recordings',
        sa.column('id', sa.UUID),
        sa.column('audio_file_id', sa.UUID)
    )
    stems_table = sa.table('stems',
        sa.column('recording_id', sa.UUID),
        sa.column('audio_file_id', sa.UUID)
    )

    # Use a subquery to find the audio_file_id for each recording from its stems
    # We use array_agg and take the first element because min/max are not defined for UUIDs
    subquery = (
        sa.select(sa.func.array_agg(stems_table.c.audio_file_id)[1])
        .where(stems_table.c.recording_id == recordings_table.c.id)
        .select_from(stems_table)
        .scalar_subquery()
    )

    # Update the audio_file_id in the recordings table
    op.execute(
        recordings_table.update()
        .values(audio_file_id=subquery)
        .where(recordings_table.c.audio_file_id.is_(None))
    )

    # Delete children of orphaned recordings first to satisfy foreign key constraints
    op.execute("""
        DELETE FROM stems WHERE recording_id IN (
            SELECT id FROM recordings WHERE audio_file_id IS NULL
        )
    """)
    op.execute("""
        DELETE FROM clips WHERE recording_id IN (
            SELECT id FROM recordings WHERE audio_file_id IS NULL
        )
    """)
    
    # Now delete the orphaned recordings
    op.execute("DELETE FROM recordings WHERE audio_file_id IS NULL")

    # Finally, make the column non-nullable
    op.alter_column(
        "recordings", "audio_file_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recordings', 'audio_file_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
