"""Add jobs table for async processing

Revision ID: 6bca8a156b3a
Revises: 8453cb11d724
Create Date: 2025-10-31 02:14:46.982583

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6bca8a156b3a"
down_revision: Union[str, Sequence[str], None] = "8453cb11d724"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("verification_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("recording_id", sa.Uuid(), nullable=False),
        sa.Column("audio_file_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("output_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["audio_file_id"],
            ["audio_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recordings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_audio_file_id"), "jobs", ["audio_file_id"], unique=False)
    op.create_index(op.f("ix_jobs_job_id"), "jobs", ["job_id"], unique=True)
    op.create_index(op.f("ix_jobs_profile_id"), "jobs", ["profile_id"], unique=False)
    op.create_index(op.f("ix_jobs_recording_id"), "jobs", ["recording_id"], unique=False)
    op.create_index(
        op.f("ix_jobs_verification_token"), "jobs", ["verification_token"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_verification_token"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_recording_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_profile_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_job_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_audio_file_id"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
