# Koyeb deployment configuration for Stemset backend
app:
  name: stemset-api
  services:
    - name: api
      type: web
      instance_type: free  # Free tier: 512MB RAM, 0.1 vCPU
      ports:
        - port: 8000
          protocol: http
      env:
        - key: PORT
          value: "8000"
        - key: PYTHON_VERSION
          value: "3.13"
        - key: STEMSET_BYPASS_AUTH
          value: "false"

        # OAuth configuration (set in Koyeb dashboard)
        - key: GOOGLE_CLIENT_ID
          scope: secret
        - key: GOOGLE_CLIENT_SECRET
          scope: secret
        - key: JWT_SECRET
          scope: secret
        - key: OAUTH_REDIRECT_URI
          scope: secret  # e.g., https://stemset-api.koyeb.app/auth/callback
        - key: FRONTEND_URL
          scope: secret  # e.g., https://stemset.pages.dev

        # R2 configuration (set in Koyeb dashboard)
        - key: R2_ACCOUNT_ID
          scope: secret
        - key: R2_ACCESS_KEY_ID
          scope: secret
        - key: R2_SECRET_ACCESS_KEY
          scope: secret
        - key: R2_BUCKET_NAME
          scope: secret
        - key: R2_PUBLIC_URL
          scope: secret  # Optional: public R2 bucket URL

      build:
        type: buildpack
        buildpack: python
      regions:
        - was  # Washington (or choose closest to your users)
      scaling:
        min: 1
        max: 1
      healthcheck:
        http:
          path: /api/profiles
          port: 8000

# Paths to monitor (only redeploy if these change)
build:
  watch_paths:
    - src/**
    - pyproject.toml
    - uv.lock
    - Dockerfile
    - .dockerignore
    - config.yaml
    - .koyeb/**
