name: Modal CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy modal workrer
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
       
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up venv
        run: |
          uv sync --frozen

      - name: Deploy job
        run: |
          uv run modal deploy src/modal_worker/worker.py
